name: flutter-version-number
description: 'Reads the version number of the pubspec.yaml'
outputs:
  version-number:
    description: "Version number"
    value: ${{ steps.read-yaml.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: read-yaml
      run: |
        VERSION=`cat pubspec.yaml | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs`
        echo "::set-output name=version::$(echo $VERSION)"
      shell: bash
