name: netzpolitik_mobile
description: A cross-plattform flutter mobile app for reading netzpolitik.org articles

publish_to: 'none'

version: 1.4.0+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^6.0.0
  json_annotation: ^4.1.0
  http: ^0.13.3

  flutter_html: ^2.1.2
  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.1.0
  html_unescape: ^2.0.0
  paging: ^0.1.0
  expandable: ^5.0.1
  url_launcher: ^6.0.10
  flutter_search_bar: ^3.0.0-dev.1
  assets_audio_player: ^3.0.3+6
  cached_network_image: ^3.1.0
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.4.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  package_info: ^2.0.2
  shared_preferences: ^2.0.7
  google_fonts: ^2.1.0
  in_app_review: ^2.0.3
  share: ^2.0.4
  flutter_email_sender: ^5.0.2
  flutter_local_notifications: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.1
  effective_dart: ^1.3.2
  json_serializable: ^5.0.0
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/netzpolitik_icon.png"

flutter_launcher_name:
  name: "Netzpolitik"

flutter:
  uses-material-design: true

  assets:
    - localizations/
    - assets/


