name: netzpolitik_mobile
description: A cross-plattform flutter mobile app for reading netzpolitik.org articles

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^4.3.2+2
  json_annotation: ^3.1.0
  http: ^0.12.2

  flutter_html: ^0.11.1
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.10.0
  html_unescape: ^1.0.2
  paging: ^0.1.0
  expandable: ^4.1.4
  url_launcher: ^5.2.7
  flutter_search_bar: ^2.1.0
  assets_audio_player: ^2.0.0+1
  cached_network_image: ^2.3.3
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.2
  effective_dart: ^1.3.0
  json_serializable: ^3.5.0
  build_runner: ^1.10.4
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/netzpolitik_icon.png"

flutter_launcher_name:
  name: "Netzpolitik"

flutter:
  uses-material-design: true

  assets:
    - localizations/
    - assets/


