name: wordpress_blog_app_template
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons:

  provider:
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic:
  effective_dart:

flutter:
  uses-material-design: true

  assets:
    - localizations/


