name: wordpress_blog_app_template
description: A generic flutter app template for wordpress apps using Wordpress Rest API

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider:
  json_annotation:
  http:

  flutter_html:
  cupertino_icons:
  font_awesome_flutter:
  html_unescape:
  paging:
  expandable:
  url_launcher:
  flutter_search_bar:
  assets_audio_player:

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic:
  effective_dart:
  json_serializable:
  build_runner:
  flutter_launcher_icons:
  flutter_launcher_name:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/netzpolitik_icon.png"

flutter_launcher_name:
  name: "Netzpolitik"

flutter:
  uses-material-design: true

  assets:
    - localizations/
    - assets/


