name: netzpolitik_mobile
description: A cross-plattform flutter mobile app for reading netzpolitik.org articles

publish_to: 'none'

version: 1.5.3+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^6.1.2
  json_annotation: ^4.9.0
  http: ^1.2.2

  flutter_html: ^3.0.0-beta.2
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  html_unescape: ^2.0.0
  expandable: ^5.0.1
  url_launcher: ^6.3.1
  #assets_audio_player: ^3.1.1
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  package_info: ^2.0.2
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  in_app_review: ^2.0.10
  share: ^2.0.4
  flutter_email_sender: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.1
  effective_dart: ^1.3.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/netzpolitik_icon.png"

flutter_launcher_name:
  name: "Netzpolitik"

flutter:
  uses-material-design: true

  assets:
    - localizations/
    - assets/


