name: flutter-android-build
description: 'Build Android apk from flutter project'
inputs:
  release:
    description: 'If set to `true`, it will run assembleRelease, otherwise assembleDebug'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - run: flutter pub get
      shell: bash
    - run: flutter pub run build_runner build --delete-conflicting-outputs
      shell: bash
    - run: |
        cd android
        if [ ${{ inputs.release }} = "true" ]; then
          ./gradlew assembleRelease
        elsecd
          ./gradlew assembleDebug
        fi
      shell: bash