name: flutter-android-build
description: 'Build Android apk from flutter project'
runs:
  using: "composite"
  steps:
    - run: flutter pub get
      shell: bash
    - run: flutter pub run build_runner build --delete-conflicting-outputs
      shell: bash
    - run: cd android && ./gradlew assembleDebug
      shell: bash