name: flutter-analyze
description: 'Runs flutter analyze'
runs:
  using: "composite"
  steps:
    - run: flutter pub get
      shell: bash
    - run: flutter pub run build_runner build --delete-conflicting-outputs
      shell: bash
    - run: flutter analyze
      shell: bash