name: flutter-test
description: 'Runs flutter test'
runs:
  using: "composite"
  steps:
    - run: flutter pub get
      shell: bash
    - run: flutter pub run build_runner build --delete-conflicting-outputs
      shell: bash
    - run: flutter test
      shell: bash