
title: netzpolitik.org - Mobile
email: niklas@lehnfeld.net
description: Inoffizielle Mobile App zum Mitlesen aller netzpolitik.org Artikel.

twitter_username: nlehnfeld
github_username:  niklaslehnfeld
linkedin_username: lehnfeld

theme: minima
plugins:
  - jekyll-feed

